---
 Title: "About Me"
---

<center> 

## About Me 

**Introductions:** Hi! My name is Chukwubunkem (Chi-Chi), I am a Nigerian immigrant, sister to two, friend and coworker to many. I am a first year, full-time student of Macalester College, to be a junior in fall 2025. Before college, I resided in Detroit, MI. Currently in college, my interest is in biostatistics, with a double major in both statistics and biology. Additionally, I am pursuing a minor in sociology. 

**Primary interests:** Primarily, I am interested in graphical and statistical models, I enjoy thinking about machine learning, machine learning models (and their limitations) as well as the best ways in which to analyze and present information in a way that is most efficient and easily understandable for the average user. Furthermore, I am interested in statistical applications for biology and sociology with a particular interest in public, physical, and mental health.

**Personal and academic goals:** After completing my bachelor’s degree, I plan to
pursue my master’s and doctoral degrees in the areas of exploration of statistical theory,
and artificial intelligence learning models in the healthcare field. I also plan to participate
heavily in research areas of both sociology and biology, utilizing statistical research
methods to deeply analyze and critically engage with these fields. Other research
interests include furthering my programming abilities, honing my data analysis skills,
and exploring different programming languages. Finally, my ultimate career goal is to
contribute immensely to the fields of public health and biostatistics.


**Relevant classes**: *Introduction to Data Science (Statistics/Computer Science 112)*, *Introduction to Computer Science (COMP 123)*, *Prius or Pickup? Political Divides and Social Class (Sociology 150)*, *Introduction to Statistic Modeling (Statistics 155)*, *Genetics (Biology 190)*, *Linear Algebra (Mathematics 236)*, *Statistical Machine Learning (Statistics 253)*, *Sociology of Mental Health (Sociology 294)*
