---
title: "Leadership"
---

<center> 

## Transformative Pedagogies Institute 

Transformative pedagogy is a teaching method that encourages students and teachers alike to critically examine their previous and current beliefs, values, and knowledge. It aims to help people develop a sense of critical consciousness, agency, and empathy to appreciate different perspectives. The Transformative Pedagogies Summer Institute is one component of Macalester's three-pronged initiative that focuses on transforming what is taught and how it is taught at Macalester. I am extremely elated to be a part of this initiative and to help create a more inclusive, diverse, and respectful environment within the classrooms. I personally relate to this topic. As an African immigrant from Nigeria, the way in which I was raised and the intersectional world view that I hold are unique to me. Because of this, I don't always feel that my opinion and/or suggestions are valued in classroom settings.

For the most part, the people that I interact with in my classes, both professors and students alike, do not look like me, nor think like me, and thereby cannot relate to my experiences and the building blocks on which I stand to form my worldview and opinions. These experiences are common among people who have marginalized identities, and they shouldn't be. This is the driving force inspiring me to create more enriching and diverse classrooms so that people don't have to feel the same way that I have in the past.

In Macalester's transformative pedagogies institute, I work with a team under the leadership of Professor Ebony Aya, a scholar in her own right, to cultivate a learning environment for both professors and students alike, learning rich in perspective, understanding, and empathy. Our team is composed of many professors from various departments and a diverse array of students. We have all come together with an awareness that growth and change need to happen at and beyond Macalester. With this in mind we work to accomplish a goal to create classrooms that are more centered on developing a sense of critical consciousness and empathy towards differing opinions.

Additionally, this program initiates learning how to navigate conversations about race, upbringing, and culture in a way that appreciates, validates, and creates learning opportunities for every person's individual experience, no matter how different it might be from our own. I will close with a quote that I like from a Macalester graduate, Gabby Whitehurst, who said, "In a society that runs off of complacency and a stunted imagination, building your capacity to just think is extremely powerful. [Acting] without introspection doesn't necessarily lead to growth and is often reactionary, rather than being rooted in omnipresent love for human rights," and within this Transformative Pedagogies Institute, I have a personal goal to implement these words within my work and life.

More information about this initiative [here](https://www.macalester.edu/serie-center/transforming-our-pedagogies/). 

Read my full reflection from my experience [here](https://docs.google.com/document/d/1Ljwy6ZgMXN1Dst37n0Hh1-yahdy0i9H63c6WsVhUHYo/edit?usp=sharing).

## Skyline Towers Volunteer 

As someone who deeply values family and a caring community, I found it extremely hard to leave my family, uncles, cousins, and friends to move from Detroit, MI, to St. Paul, MN. This was hard because I was going to miss the people that I have loved and known all my life. I wasn't sure if I would be able to make connections like that again. As a result of this experience, I made it a mission to commit to finding, if not creating, a caring community of my own. I was able to find this through volunteering with the Commonbond communities within the Skyline Tower of St. Paul. Commonbond is an affordable housing nonprofit that serves low-income communities in Minnesota, Wisconsin, Iowa, and South Dakota. My commitment to serving these communities in my little way is a welcome opportunity, which I would not gain any other way.

In my position as a Commonbond volunteer, I worked to build trust and a community bond between myself and the kids under my care, utilizing social-emotional learning (SEL) activities along with making sure that we were completing their assigned reading for their grade level. I made sure to exercise patience, understanding, and respect in my interactions, ensuring that I was setting a good example for the kids around me. I worked to adapt to different grade levels and learning styles with the aim of helping each individual student meet their individual needs. That is, to successfully complete their assignments and reading goals. I also led and facilitated discussions with the kids with the aim of achieving two practical reading goals per week.

## Orientation Leader 

In furtherance to my goal of community engagement, this past summer, I served as an orientation leader to 16 freshmen individuals with diverse backgrounds and interests. In this role, I led, planned, and facilitated one-on-one discussions, group discussions, and organized group meetings covering such topics as what it means to be a part of Macalester College, including providing them with information regarding mental, physical, and sexual health, Title IX, academic integrity policies, etc. I also advised them on how to be successful in college, showed them where their classes are, and told them quirkities and traditions of Macalester College.

I also organized a night when everyone from our original orientation group reconvened to share letters that they wrote to themselves with the group, catch up with some of the first people that they met at Macalester, enjoy good food, and for me, to catch up with them and their challenges. During this meeting, based on their challenges, I will check if there is additional assistance that I can provide to help them have a fruitful Macalester education and experience. Also at this meeting, we reflected on their first thoughts when they first arrived on campus and explored what had changed since then.

The aim of all this was to help these students feel at home at Macalester College. The bottom line is that college is a major commitment. Macalester is a place where they will not only find forever friends but a second home and a welcoming community. A community that will be there during the thick and thin days of college life. Additionally, a place where they will be intellectually, emotionally, and physically challenged in a way that no other institution can.

For me, I have enjoyed this experience and have learned a lot about how to create and sustain a community as well as how to effectively lead a group while also prioritizing everyone's individual needs.

## Mac Mentors 

The Mac Mentorship Program is a year-long mentoring program between Macalester students and high school juniors and seniors in the TRIO Upward Bound program at North Hennepin Community College (NHCC). The program begins in the fall semester mentoring senior students as they finalize applications and get ready for adjusting to college life. Then, in the spring, we focus our attention to students in their junior year of high school. In this, we guide the students as they looking for the right college, and as they craft their personal statement, look for scholarships, and this continues into the fall semester of their senior year. 

I am happy to be a mentor as I have a lot to share from my college application process and college experience. With this experience, I get to advocate that while the college admissions process is not easy, it is incredibly rewarding. Furthermore, as someone who's perspective is not always advocated for, I am happy to share my unique perspective and use my experiences to help navigate any difficulties that others face as they begin their college application, secure admission into college, and in their preparation for the challenges that are to come with college. There is no question that with this experience, there is much to learn and skills to repurpose.

## Rondo Community Outreach Library - Teaching Assistant

In the 1930s, Rondo Avenue was at the heart of St. Paul, Minnesota's largest Black neighborhood. One that brought community, vital liveliness, and an escape, distracting from the struggle that simply being a Black American brought on throughout the day. The construction of I-94 in 1968 divided this community and displaced thousands of Black Americans into a rather racially segregated and discriminatory housing market. The community has never been the same since. Though there are initiatives to keep the Rondo community alive. The Rondo Community Outreach Library hopes to bring back the community that once was. The library is also home to a special collection of Rondo artifacts and information, capturing and showcasing the rich history of the neighborhood.

As we exist in a digital age, there is an increasing amount of mandatory technology usage due to jobs, media, news, communication, and more being normally found on the internet. Therefore, adaptation to this new digital age must occur among older populations of people. It is becoming ever more necessary to become more knowledgeable about online resources as doctor appointments, meetings, and other activities have switched to online interfaces. Based on this, in since October of 2022, Jenaya Myvett, an instructor and Rondo Black American community engagement specialist, made it her mission to make sure that a lack of technology is not a hindrance to the Rondo community's ability to apply to jobs, communicate with others, schedule doctor's appointments, simply peruse the internet, and perform other internet activities. To do this, she constructed a technology certification class in which to unite the community and help them achieve digital literacy at the same time.

In my position, I am tasked with answering questions, explaining concepts, and making sure that the class is running smoothly. I effectively assist 10+ adults per week in earning certificates in digital literacy. I actively proctor 4+ practice exams per week, helping students gain competency in digital literacy. Additionally, I build connections between myself and the Rondo community. This position has been one of both teaching and learning for me in a way that I could have never imagined, and I am so grateful to Jenaya Myvett, the volunteers, and the students that make this a reality.

**Credit:** [https://www.macalester.edu/community-engagement/academiccivicengagement/historic-rondo-neighborhood/](https://www.macalester.edu/community-engagement/academiccivicengagement/historic-rondo-neighborhood/)
\
**More information on Rondo:** [here.](https://libguides.mnhs.org/rondo/ov and https://reconnectrondo.com/vision/)

## Sankofa Event Facilatator 

*In Black Ink*, is a state-wide, grassroots, non-profit organization that creates spaces where the inter-generational stories of Minnesotans of African heritage can be shared, documented, and archived. *In Black Ink* provides publishing arts initiatives and opportunities to communities that have been disenfranchised historically and continue to suffer the consequences on this presently. Yearly, *In Black Ink* hosts an inter-generational, Black gathering, centered around the Sankofa philosophy. 

Within this opportunity I was able to facilitate meaningful and insightful conversations about issues pertinent to Black culture. By engaging in open and honest dialogue, I gained a deeper understanding of diverse perspectives, challenged my own biases, and developed stronger intercultural and inter-generational communication skills. 

## Teaching Assistant (Preceptor)

For the Introduction to Data Science (COMP 112) class, I work to hold drop-in tutoring sessions, grade homework, and assist students within class time. By assisting students, I have enhanced my technical and interpersonal skills tremendously. I have also solidified my foundational understanding of core data science concepts. Furthermore, I have improved my problem-solving abilities and gained more expansive expertise within Rstudio. Lastly, I developed effective communication and teaching skills, including the ability to explain complex ideas clearly, actively listen, and provide constructive feedback. This experience fostered both my professional and personal growth.

## IES Abroad Correspondent

Full detailed description *coming soon*. 

More information [here.](https://www.iesabroad.org/correspondents/chi-chi-okezie)

## Reach The World Blogger 

While studying abroad in Cape Town, South Africa, I wrote about my experiences on the Reach the World platform. On this platform, I partnered with a fourth grade math classroom to inspire these young students and young students everywhere to stay curious about their surroundings and the greater world beyond them. By sharing my experiences, I hoped that my stories encouraged them to dream big, imagine themselves as travelers coming along my journey with me, and to notice connections between my experiences and their own lives.

Access my blog posts [here.](https://www.reachtheworld.org/chi-chis-journey-south-africa)

Read more about Reach the World and their mission [here.](https://about.reachtheworld.org/what-we-do/)


## Sister's Inc. Volunteer

While in Cape Town, South Africa, I worked as a volunteer for the Sister's Incorporated organization. 

Over the past 60 years in Cape Town, Sister's Incorporated has worked to protect, support, and empower single women and their children who are survivors of domestic violence, abuse, and the stigmatization that comes with this. The organization provides a safe place for women and children, emphasizing non-judgmental care and empowerment for every individual who enters its doors. As I volunteered here, I can speak to this as I feel that during my time here I also felt wholly embraced, welcomed and cared for upon entrance and even more so as I got to know the residents and staff members. 

Read more about Sisters Incorporated and the work that they do [here.](https://sisters.org.za/who-we-are/)

## Langa High School Tutor 

While in Cape Town, South Africa, I worked as a volunteer for Langa High School, working to teach Maths and English saturday sessions. 

Established in 1937, Langa High School is the oldest Black secondary school in South Africa. During the 1970s and 1980s, students at Langa High School were often involved in political activism and uprisings making the school a significant site for understanding the experiences and resilience of Black South Africans during apartheid. While the school's mission is not explicitly stated on its website, a mural on one of its walls reads, “Enter to learn, leave to serve.” This phrase, discussed in Betts (2020), reflects a guiding ethos that encourages students to use the knowledge they gain in school to serve and uplift the Langa community. As Betts (2020) explains, the phrase establishes a precedent for each student to go forth into their community with the knowledge gained from the school, to then be of service to others, enhancing the lives of others, and creating better citizens.

Langa High's mission and practice are shaped by the broader context of Langa Township, established in 1927 as one of the first areas in Cape Town designated for Africans under segregationist urban planning. The township was intentionally designed with strict spatial control giving the community limited access to multiple roads that could be blocked during times of unrest, reflecting the apartheid state’s broader strategy of containment and surveillance (Musemwa, 1993). Historically, residents of Langa faced systemic deprivation, including high rents, poor transport access, and inadequate municipal services (Musemwa, 1993). Despite these constraints, Langa became a focal point for social and political resistance, and the high school has served as an educational and symbolic space for empowerment within this marginalized community.

Betts, B. (2020) Enter to learn, leave to serve, Tieonline.com. Available at: [https://www.tieonline.com/article/2679/enter-to-learn-leave-to-serve](https://www.tieonline.com/article/2679/enter-to-learn-leave-to-serve) (Accessed: October 29, 2025).

 Musemwa, M. (1993) Aspects of the social and political history of Langa Township, Cape Town, 1927-1948, Uct.ac.za. Available at: [https://open.uct.ac.za/items/ef4ec635-f6fa-4aa3-bbd5-b09c80ed7fa8](https://open.uct.ac.za/items/ef4ec635-f6fa-4aa3-bbd5-b09c80ed7fa8) (Accessed: October 29, 2025).
